export const config = {
	"apiURL": `${location.protocol}//${location.host}/api/v1`,
	"wsURL": `ws${location.protocol == 'https:' ? 's' : ''}://${location.host}/ws/v1`,
	"ingressURL": {
		"rtmp": "rtmp://ingress.media.kukoon.de/stream/{ID}",
		"ws": "wss://edge01.media.kukoon.de/stream/ws/stream/{ID}?direction=send&transport=tcp",
	},
	"sourceURL": "https://edge01.media.kukoon.de/stream/stream/{ID}/playlist.m3u8",
	"defaultChannel": "kukoon",
	// "defaultChannel": "df1555f5-7046-4f7a-adcc-195b73949723",
	"defaultLang": "de",
	"colors": {
		"calendar": [
			'red darken-1', 'pink darken-1', 'purple darken-1',
			'deep-purple darken-1', 'indigo darken-1', 'blue darken-1',
			'light-blue darken-1', 'cyan darken-1', 'teal darken-1',
			'green darken-1', 'light-green darken-1', 'lime darken-1',
			'yellow darken-2', 'amber darken-1', 'orange darken-1',
			'deep-orange darken-1', 'brown darken-1', 'blue-grey darken-1',
			'grey darken-1'
		]
	},
	"chat": {
		"anonym": {
			"names": [
				"Affe",
				"Amsel",
				"Armeise",
				"Dino",
				"Esel",
				"Eule",
				"Fink",
				"Fisch",
				"Fliege",
				"Forelle",
				"Frosch",
				"Fuchs",
				"Gans",
				"Giraffe",
				"Hahn",
				"Hamster",
				"Hase",
				"Hund",
				"Kanguru",
				"Katze",
				"Käfer",
				"Löwe",
				"Maulwurf",
				"Maus",
				"Pinguin",
				"Pudel",
				"Ratte",
				"Raupe",
				"Robben",
				"Schmetterling",
				"Spatz",
				"Spinne",
				"Tiger",
				"Uhu",
				"Vogel",
				"Waschbär",
				"Wolf",
				"Ziege",
			]
		},
	},
}
