export const config = {
	// "apiURL": `http://localhost:8090/api/v1`,
	// "wsURL": `ws://localhost:8090/ws/v1`,
	// "apiURL": `https://v2-dev.media.kukoon.de/api/v1`,
	// "wsURL": `wss://v2-dev.media.kukoon.de/ws/v1`,
	"apiURL": `${location.protocol}//${location.host}/api/v1`,
	"wsURL": `ws${location.protocol == 'https:' ? 's' : ''}://${location.host}/ws/v1`,
	"sourceURL": "https://edge01.media.kukoon.de/stream/stream/{ID}/playlist.m3u8",
	"defaultChannel": "kukoon",
	// "defaultChannel": "df1555f5-7046-4f7a-adcc-195b73949723",
	"defaultLang": "de",
	"chat": {
		"anonym": {
			"names": [
				"Affe",
				"Amsel",
				"Armeise",
				"Dino",
				"Esel",
				"Eule",
				"Fink",
				"Fisch",
				"Fliege",
				"Forelle",
				"Frosch",
				"Fuchs",
				"Gans",
				"Giraffe",
				"Hahn",
				"Hamster",
				"Hase",
				"Hund",
				"Kanguru",
				"Katze",
				"Käfer",
				"Löwe",
				"Maulwurf",
				"Maus",
				"Pinguin",
				"Pudel",
				"Ratte",
				"Raupe",
				"Robben",
				"Schmetterling",
				"Spatz",
				"Spinne",
				"Tiger",
				"Uhu",
				"Vogel",
				"Waschbär",
				"Wolf",
				"Ziege",
			]
		},
	},
}
