name: Build UI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: Install packages
        run: yarn install
      - name: Install Lint
        run: yarn lint
      - name: Install Build
        run: yarn build
