name: Build UI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened,synchronize,reopened]
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install
      - name: Check with lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/
      - name: Upload to Server
        uses: up9cloud/action-rsync@master
        env:
          USER: ${{secrets.DEPLOY_SSH_USER}}
          HOST: ${{secrets.DEPLOY_SSH_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          ARGS: -rzh -O --delete-after --exclude=rtmp/ --exclude=stream/ --exclude=videos/
          SSH_ARGS: '-p ${{secrets.DEPLOY_SSH_PORT}} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: dist/
          TARGET: /
